### ISSUE TITLE
ios production build failing

### ISSUE THREAD

**Issue by veeramarni** [sysgears/spinjs#33]
When running production build with spin, it fails with the following error.

Errors
---
```
ERROR in ./node_modules/@expo/vector-icons/createIconSet.js
Module build failed: TypeError: /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/@expo/vector-icons/createIconSet.js: Cannot read property 'add' of undefined
    at ScopeTracker.addReference (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:55:36)
    at ReferencedIdentifier (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:190:28)
    at newFn (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/visitors.js:318:17)
    at bfsTraverse (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:34:43)
    at Mangler.collect (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:269:9)
    at Mangler.run (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:70:14)
    at PluginPass.exit (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:589:19)
    at newFn (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/path/context.js:48:17)
 @ ./node_modules/@expo/vector-icons/index.js 1:680-706
 @ ./src/client/modules/contact/index.jsx
 @ ./src/client/modules/index.js
 @ ./src/mobile/App.js
 @ ./src/mobile/AwakeInDevApp.js
 @ ./src/mobile/index.js
 @ multi ./node_modules/spinjs/react-native-polyfills/react-native-polyfill-16.js raf/polyfill ./src/mobile/index.js

ERROR in ./node_modules/expo/src/AuthSession.js
Module build failed: TypeError: /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/expo/src/AuthSession.js: Cannot read property 'add' of undefined
    at ScopeTracker.addReference (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:55:36)
    at ReferencedIdentifier (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:190:28)
    at newFn (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/visitors.js:318:17)
    at bfsTraverse (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:34:43)
    at Mangler.collect (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:269:9)
    at Mangler.run (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:70:14)
    at PluginPass.exit (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:589:19)
    at newFn (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/path/context.js:48:17)
 @ ./node_modules/expo/src/Expo.js 1:1146-1170
 @ ./src/mobile/AwakeInDevApp.js
 @ ./src/mobile/index.js
 @ multi ./node_modules/spinjs/react-native-polyfills/react-native-polyfill-16.js raf/polyfill ./src/mobile/index.js

ERROR in ./node_modules/expo/src/Location.js
Module build failed: TypeError: /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/expo/src/Location.js: Cannot read property 'add' of undefined
    at ScopeTracker.addReference (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:55:36)
    at ReferencedIdentifier (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:190:28)
    at newFn (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/visitors.js:318:17)
    at bfsTraverse (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:34:43)
    at Mangler.collect (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:269:9)
    at Mangler.run (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:70:14)
    at PluginPass.exit (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-plugin-minify-mangle-names/lib/index.js:589:19)
    at newFn (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/starter-kit/node_modules/babel-traverse/lib/path/context.js:48:17)
 @ ./node_modules/expo/src/Expo.js 1:239-260 1:3293-3314
 @ ./src/mobile/AwakeInDevApp.js
 @ ./src/mobile/index.js
 @ multi ./node_modules/spinjs/react-native-polyfills/react-native-polyfill-16.js raf/polyfill ./src/mobile/index.js
```

The issue seems to be related to `babel-plugin-minify` as mentioned [here](https://github.com/babel/minify/issues/556)

**Comment by veeramarni** [comment]
The workaround for this issue to either remove `babel-preset-minify` or set `mangle` to false. 

https://github.com/sysgears/spinjs/blob/master/src/plugins/ReactNativePlugin.ts#L46

**Comment by vlasenko** [comment]
@veeramarni Thank you very much for investigating this issue and finding workaround!

**Comment by veeramarni** [comment]
@vlasenko thanks for fixing it.
