### ISSUE TITLE
Eslint fails on Apollo Universal App's client directory.

### ISSUE THREAD

**Issue by adam-s** [sysgears/spinjs#36]
Version 0.4.72 of sysgears/spinjs causes the files in the client directory of Apollo Universal Starter Kit to not validate. It says cannot find module '../node_modules/eslint/.spinrc.json'. It seems new .js files are linted correctly whereas .jsx files are not so it might have something to do with the extension name. Also, when I copy and post .spinrc.json into the /node_modules/eslint/.spinrc.json directory it works fine. So for some reason it is looking for .spinrc.json in the wrong directory.

**Comment by vlasenko** [comment]
@adam-s How can I reproduce this? I have cloned the latest version of the kit and run `yarn lint`, I don't see any validation errors

**Comment by adam-s** [comment]
It might be that I'm using PhpStorm for my IDE and I'm running it with Ubuntu / Linux. Nonetheless, I'm having difficulties having the loader load files from other Ant Design packages like [rc-drawer-menu](https://www.npmjs.com/package/rc-drawer-menu).

**Comment by adam-s** [comment]
It might be an issue with my IDE, PhpStorm. However, I'm experiencing other problems with an Ant Design package, rc-drawer-menu, sometimes loading assets and sometimes not loading assets which I'll be looking into now.

**Comment by adam-s** [comment]
I followed the instructions in the gitter channel to clear the [yarn cache and reload the node_modules](https://gitter.im/sysgears/apollo-fullstack-starter-kit?at=5a59b20bae53c15903e0f96e). Things seem to work with eslint now. 

You need to clean node_modules and yarn cache
Remove node_modules dir, i.e.` rm -rf node_modules`
And clear yarn cache via `yarn cache clean`
Then do `yarn`
And then do `yarn watch`
Oh, and remove build folder too
I will do the same meantime, to compare results

**Comment by adam-s** [comment]
Sorry, I still have the issue. Here is the error output I'm getting.
Error: Cannot find module '/home/adam/PhpstormProjects/joboty-admin/node_modules/eslint/.spinrc.json'

Error: Cannot find module '/home/adam/PhpstormProjects/joboty-admin/node_modules/eslint/.spinrc.json'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.resolve (internal/module.js:18:19)
    at Function.requireModule.resolve (/home/adam/PhpstormProjects/joboty-admin/node_modules/spinjs/src/requireModule.ts:11:15)
    at Function.Spin.require.require.resolve (/home/adam/PhpstormProjects/joboty-admin/node_modules/spinjs/src/Spin.ts:30:70)
    at new ConfigRc (/home/adam/PhpstormProjects/joboty-admin/node_modules/spinjs/src/configRc.ts:17:71)
    at Object.createConfig [as default] (/home/adam/PhpstormProjects/joboty-admin/node_modules/spinjs/src/createConfig.ts:47:18)
    at Object.<anonymous> (/home/adam/PhpstormProjects/joboty-admin/node_modules/spinjs/src/webpack.config.ts:3:28)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/adam/PhpstormProjects/joboty-admin/node_modules/spinjs/webpack.config.js:3:18)
    at Module._compile (module.js:641:30)
Process finished with exit code -1

**Comment by vlasenko** [comment]
@adam-s Okay, I'm going to fix that soon. If you need workaround right now, add this file to the root of your project, next to `package.json`:
https://github.com/sysgears/apollo-universal-starter-kit/blob/workspaces-lerna/packages/client/webpack.config.lint.js
And change this line:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/.eslintrc#L30
to:
`"config": "webpack.config.lint.js"`

**Comment by vlasenko** [comment]
@adam-s I have pushed the fix above into the kit repo:
https://github.com/sysgears/apollo-universal-starter-kit/commit/0e1b7e7cf902cc5ee41ace2360e3fbdd2725a1e1
Would be nice if you could check does it fixes the problem and report here
