### ISSUE TITLE
docker question

### ISSUE THREAD

**Issue by veeramarni** [sysgears/spinjs#49]
Do we need to install any specific package for `spinjs` to work in the container? With the new version, it seems failing for us with following error. 

```
> sample-stack@0.3.0 spin:watch /usr/src/app/fullstack-pro
> spin watch

Error: Cannot find module './lib/cli'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/fullstack-pro/node_modules/spinjs/spin.js:4:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

Docker file
--
```
FROM node:8.9.4

COPY startup /opt/startup
COPY sshd_config /etc/ssh/

RUN npm install -g pm2 \
     && mkdir -p /home/LogFiles \
     && echo "root:Docker!" | chpasswd \
     && echo "cd /home" >> /etc/bash.bashrc \
     && apt update \
     && apt install -y --no-install-recommends openssh-server vim curl wget tcptraceroute \
     && cd /opt/startup \
     && npm install \
     && chmod 755 /opt/startup/init_container.sh

EXPOSE 2222 8080

ENV PM2HOME /pm2home

ENV PORT 8080
ENV WEBSITE_ROLE_INSTANCE_ID localRoleInstance
ENV WEBSITE_INSTANCE_ID localInstance

WORKDIR /usr/src/app
```

**Comment by veeramarni** [comment]
Never mind something funky with `eslint` after reinstalling it, I don't see that problem.

https://github.com/eslint/eslint/issues/6983
